name: gym
description: "A PWA for tracking and comparing my and my friend's gym progress."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  cloud_firestore: 4.14.0
  device_preview: ^1.1.0
  dio: ^5.4.0
  firebase_auth: 4.16.0
  firebase_core: 2.24.2
  firebase_core_web: 2.10.0
  firebase_storage: 11.5.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_iconly: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  gradient_circular_progress_indicator: ^0.0.4
  intl: ^0.18.1
  ionicons: ^0.2.2
  json_annotation: ^4.8.1
  list_ext: ^1.0.6
  logging: ^1.2.0
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
    lottie: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/auth/
    - assets/not-found/
    - assets/onboarding/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
